import type { RackConfig, PlacedDevice } from '../state/types';
import { getDevice } from '../data/devices';
import JSZip from 'jszip';

/**
 * Generate JSCAD JavaScript code from a rack configuration (for export)
 */
export function generateScadCode(config: RackConfig, _useConfigPreview = true): string {
  const lines: string[] = [];

  // Header with timestamp
  lines.push('/**');
  lines.push(' * Rack Configuration - JSCAD Script');
  lines.push(` * Generated by Rack Configurator on ${new Date().toISOString()}`);
  lines.push(' *');
  lines.push(` * Rack: ${config.rackU}U, ${config.earStyle} ears, ${config.backStyle} back`);
  if (config.isSplit) {
    lines.push(` * Split at: ${config.splitPosition || 'auto'}mm`);
    lines.push(` * Left devices: ${config.leftDevices.length}`);
    lines.push(` * Right devices: ${config.rightDevices.length}`);
  } else {
    lines.push(` * Devices: ${config.devices.length}`);
  }
  lines.push(' *');
  lines.push(' * To use: Install @jscad/modeling and @jscad/stl-serializer');
  lines.push(' * Then run: node this-file.js > output.stl');
  lines.push(' */');
  lines.push('');

  // The exported config as JSON (can be loaded by the JSCAD rack generator)
  lines.push('// Rack configuration data');
  lines.push(`const rackConfig = ${JSON.stringify(config, null, 2)};`);
  lines.push('');
  lines.push('// To render, use the rack-configurator JSCAD modules:');
  lines.push('// import { generateRack } from "./jscad/rack-generator";');
  lines.push('// import { serialize } from "@jscad/stl-serializer";');
  lines.push('// const geometry = generateRack(rackConfig);');
  lines.push('// const stl = serialize({ binary: true }, geometry);');
  lines.push('');
  lines.push('module.exports = { rackConfig };');

  return lines.join('\n');
}

/**
 * Get the effective dimensions of a placed device
 */
export function getPlacedDeviceDimensions(device: PlacedDevice): {
  width: number;
  height: number;
  depth: number;
  name: string;
} {
  if (device.deviceId === 'custom') {
    return {
      width: device.customWidth || 50,
      height: device.customHeight || 30,
      depth: device.customDepth || 50,
      name: device.customName || 'Custom Device',
    };
  }

  const deviceData = getDevice(device.deviceId);
  if (deviceData) {
    // Special handling for patch panel - calculate width based on port count
    if (device.mountType === 'patch_panel') {
      const ports = device.patchPanelPorts || 6;
      const keystoneSpacing = 19; // mm per keystone slot
      return {
        width: ports * keystoneSpacing,
        height: 30, // Standard keystone visible height
        depth: 15,
        name: `${ports}-Port Patch Panel`,
      };
    }

    // Special handling for Pi 5 case mount - use case dimensions
    if (device.mountType === 'pi5_case') {
      return {
        width: 93,   // PI5_CASE_FACE_W (85 + 2*(2+1))
        height: 64,  // PI5_CASE_FACE_H (56 + 2*(2+1))
        depth: 35,   // PI5_CASE_DEPTH
        name: 'Raspberry Pi 5 Case',
      };
    }

    return {
      width: deviceData.width,
      height: deviceData.height,
      depth: deviceData.depth,
      name: deviceData.name,
    };
  }

  // Fallback for unknown device
  return {
    width: 50,
    height: 30,
    depth: 50,
    name: device.deviceId,
  };
}

/**
 * Generate a default filename based on configuration
 */
export function generateFilename(config: RackConfig, extension: string, side?: 'left' | 'right'): string {
  const parts = [`rack_${config.rackU}u`];

  if (config.isSplit) {
    parts.push('split');
    if (side) {
      parts.push(side);
    }
  }

  const deviceCount = config.isSplit
    ? side === 'left'
      ? config.leftDevices.length
      : side === 'right'
        ? config.rightDevices.length
        : config.leftDevices.length + config.rightDevices.length
    : config.devices.length;

  if (deviceCount > 0) {
    parts.push(`${deviceCount}dev`);
  }

  return `${parts.join('_')}.${extension}`;
}

/**
 * Download JSCAD code as a file
 */
export function downloadScadFile(config: RackConfig, filename?: string): void {
  const code = generateScadCode(config, false);
  const blob = new Blob([code], { type: 'text/javascript' });
  const url = URL.createObjectURL(blob);

  const a = document.createElement('a');
  a.href = url;
  a.download = filename || generateFilename(config, 'js');
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/**
 * Export configuration as JSON
 */
export function exportConfigJson(config: RackConfig): string {
  return JSON.stringify(config, null, 2);
}

/**
 * Download configuration as JSON file
 */
export function downloadConfigJson(config: RackConfig, filename = 'rack_config.json'): void {
  const json = exportConfigJson(config);
  const blob = new Blob([json], { type: 'application/json' });
  const url = URL.createObjectURL(blob);

  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/**
 * Parse configuration from JSON
 */
export function parseConfigJson(json: string): RackConfig | null {
  try {
    const config = JSON.parse(json);
    // Basic validation
    if (typeof config.rackU === 'number' && Array.isArray(config.devices)) {
      return config as RackConfig;
    }
    return null;
  } catch {
    return null;
  }
}

/**
 * Download an ArrayBuffer as a file
 */
export function downloadArrayBuffer(data: ArrayBuffer, filename: string, mimeType: string): void {
  const blob = new Blob([data], { type: mimeType });
  const url = URL.createObjectURL(blob);

  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/**
 * Download STL data
 */
export function downloadStl(data: ArrayBuffer, config: RackConfig, side?: 'left' | 'right'): void {
  const filename = generateFilename(config, 'stl', side);
  downloadArrayBuffer(data, filename, 'application/sla');
}

/**
 * Generate JSCAD code for a specific side of a split panel
 */
export function generateScadCodeForSide(config: RackConfig, side: 'left' | 'right'): string {
  const renderMode = side === 'left' ? 'left_print' : 'right_print';
  return generateScadCode({ ...config, renderMode }, false);
}

/**
 * Download both split sides as separate STL files in a ZIP
 */
export async function downloadSplitStlZip(
  leftStl: ArrayBuffer,
  rightStl: ArrayBuffer,
  config: RackConfig
): Promise<void> {
  const zip = new JSZip();

  // Generate filenames for each side
  const leftFilename = generateFilename(config, 'stl', 'left');
  const rightFilename = generateFilename(config, 'stl', 'right');

  // Add both STL files to the ZIP
  zip.file(leftFilename, leftStl);
  zip.file(rightFilename, rightStl);

  // Generate ZIP filename
  const zipFilename = `rack_${config.rackU}u_split_${config.leftDevices.length + config.rightDevices.length}dev.zip`;

  // Generate and download the ZIP
  const zipBlob = await zip.generateAsync({ type: 'blob' });
  const url = URL.createObjectURL(zipBlob);

  const a = document.createElement('a');
  a.href = url;
  a.download = zipFilename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
